//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Save_Our_Pets.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Adopciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adopciones()
        {
            this.reporte_seguimiento = new HashSet<reporte_seguimiento>();
        }
    
        public int id_adopcion { get; set; }
        [Display(Name = "Usuario")]
        [Required(ErrorMessage = "Selecione el usuario")]
        public int id_usuario { get; set; }
        [Display(Name = "Mascota")]
        [Required(ErrorMessage = "Selecione la mascota")]
        public int id_mascota { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Mascota Mascota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reporte_seguimiento> reporte_seguimiento { get; set; }
    }
}
