//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Save_Our_Pets.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Estado_salud
    {
        public int id_estado_salud { get; set; }
        [Display(Name = "Mascota")]
        [Required(ErrorMessage = "Selecione la mascota")]
        public int id_mascota { get; set; }
        [Display(Name = "Descripción")]
        public string descripcion_salud { get; set; }
    
        public virtual Mascota Mascota { get; set; }
    }
}
