//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Save_Our_Pets.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class img_mascota
    {
        public int id_imagen { get; set; }
        [Display(Name = "Mascota")]
        public int id_mascota { get; set; }
        [Display(Name = "Imagen")]
        public byte[] imagen_mascota { get; set; }
    
        public virtual Mascota Mascota { get; set; }
    }
}
