//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Save_Our_Pets.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reporte_vacunas
    {
        public int id_vacuna_aplicada { get; set; }
        [Display(Name = "Mascota")]
        public int id_mascota { get; set; }
        [Display(Name = "Vacuna")]
        public int id_vacuna { get; set; }
        [Display(Name = "Fecha aplicada")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> fecha_aplicada { get; set; }
        [Display(Name = "Fecha a aplicar nuevamente")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> fecha_a_aplicar_nueva { get; set; }
    
        public virtual Mascota Mascota { get; set; }
        public virtual Vacunas Vacunas { get; set; }
    }
}
