//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Save_Our_Pets.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class reporte_seguimiento
    {
        public int id_seguimiento { get; set; }
        public int id_adopcion { get; set; }
        public Nullable<int> visitas_seguimiento { get; set; }
        [Display(Name = "Comentario")]
        public string comentario { get; set; }
        [Display(Name = "Fecha de visita")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> fecha_visita { get; set; }
    
        public virtual Adopciones Adopciones { get; set; }
    }
}
