//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Save_Our_Pets.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class reporte_rescate
    {
        public int id_solicitud { get; set; }
        [Display(Name = "Mascota")]
        public int id_mascota { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Ingrese la dirección de su correo electrónico")]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Ingrese un correo electrónico válido")]
        public string email { get; set; }
        [Display(Name = "Teléfono")]
        [Required(ErrorMessage = "Ingrese su número de teléfono")]
        [RegularExpression("^(2|6|7)[0-9]{3}-[0-9]{4}$", ErrorMessage = "El número ingresado debe estar en el formato 2222-2222")]
        public string telefono { get; set; }
        [Display(Name = "Dirección")]
        public string direccion { get; set; }
        [Display(Name = "Descripción")]
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_reporte { get; set; }
        public Nullable<System.DateTime> fecha_rescate { get; set; }
    
        public virtual Mascota Mascota { get; set; }
    }
}
