//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Save_Our_Pets.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class save_our_petsEntities : DbContext
    {
        public save_our_petsEntities()
            : base("name=save_our_petsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adopciones> Adopciones { get; set; }
        public virtual DbSet<direccion_usuario> direccion_usuario { get; set; }
        public virtual DbSet<Especie> Especie { get; set; }
        public virtual DbSet<Estado_mascota> Estado_mascota { get; set; }
        public virtual DbSet<Estado_salud> Estado_salud { get; set; }
        public virtual DbSet<img_mascota> img_mascota { get; set; }
        public virtual DbSet<Mascota> Mascota { get; set; }
        public virtual DbSet<Raza> Raza { get; set; }
        public virtual DbSet<reporte_rescate> reporte_rescate { get; set; }
        public virtual DbSet<reporte_seguimiento> reporte_seguimiento { get; set; }
        public virtual DbSet<Reporte_vacunas> Reporte_vacunas { get; set; }
        public virtual DbSet<solicitud_adopcion> solicitud_adopcion { get; set; }
        public virtual DbSet<Tipo_usuario> Tipo_usuario { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Vacunas> Vacunas { get; set; }
    }
}
