//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Save_Our_Pets.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class solicitud_adopcion
    {
        public int id_solicitud { get; set; }
        [Display(Name = "Usuario")]
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> empleo_fijo { get; set; }
        [Display(Name = "Especie")]
        public Nullable<int> id_especie { get; set; }
        [Display(Name = "Requisitos y condiciones")]
        public Nullable<int> requisitos_condiciones { get; set; }
        [Display(Name = "Estado")]
        public Nullable<int> estado_solicitud { get; set; }
        [Display(Name = "Empleado")]
        public int id_empleado { get; set; }
    
        public virtual Especie Especie { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Usuarios Usuarios1 { get; set; }
    }
}
